### ISSUE TITLE
March 10th 2020 - Peer 2 Peer Code Review

### ISSUE THREAD

**Issue by alvaropazz** [sebGilR/newsweek#1]
Questions?
#Empty divs?
#Why are you using scripts @ the end of the body?

**Comment by sebGilR** [comment]
- Empty divs currently being used as separators but will be replaced by ::before or ::after selectors when the order of the elements is established.
- Scripts added at the end of the body as suggested by Bootstrap documentation, to allow for all the elements to load before any script executes and avoid unexpected behaviors.
